source 'https://rubygems.org'
gem 'rails', '3.2.12'
gem 'pg'
gem 'pg_search'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'compass-rails'
  gem 'compass-h5bp'
  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
  gem 'jquery-fileupload-rails'
  gem 'haml_coffee_assets'
  gem 'turbo-sprockets-rails3'
end
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-timepicker-rails'
gem 'haml-rails'
gem 'html5-rails'
gem 'coffee-script-source'
gem 'versionist'
gem 'devise'
gem 'devise_invitable'
gem 'devise_security_extension'
gem 'ejs'
gem 'doorkeeper'
gem 'activeadmin'
gem 'inherited_resources'
gem 'has_scope'
gem 'rabl'
gem 'yajl-ruby'
gem 'jquery-fileupload-rails'
gem 'oauth2'
gem 'gon'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'kaminari'
group :development do
  gem 'rack-livereload'
  gem 'guard-livereload'
  gem 'quiet_assets'
  gem 'meta_request', '0.2.0'
  gem 'mailcatcher'
  gem 'sextant'
end
gem 'activerecord-postgres-hstore'
gem "rmagick"
gem "carrierwave"
