#encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Country.delete_all
Country.create(:id=>1,:iso=>"AD",:country=>"Andorra")
Country.create(:id=>2,:iso=>"AE",:country=>"United Arab Emirates")
Country.create(:id=>3,:iso=>"AF",:country=>"Afghanistan")
Country.create(:id=>4,:iso=>"AG",:country=>"Antigua and Barbuda")
Country.create(:id=>5,:iso=>"AI",:country=>"Anguilla")
Country.create(:id=>6,:iso=>"AL",:country=>"Albania")
Country.create(:id=>7,:iso=>"AM",:country=>"Armenia")
Country.create(:id=>8,:iso=>"AO",:country=>"Angola")
Country.create(:id=>9,:iso=>"AQ",:country=>"Antarctica")
Country.create(:id=>10,:iso=>"AR",:country=>"Argentina")
Country.create(:id=>11,:iso=>"AS",:country=>"American Samoa")
Country.create(:id=>12,:iso=>"AT",:country=>"Austria")
Country.create(:id=>13,:iso=>"AU",:country=>"Australia")
Country.create(:id=>14,:iso=>"AW",:country=>"Aruba")
Country.create(:id=>15,:iso=>"AX",:country=>"Aland Islands")
Country.create(:id=>16,:iso=>"AZ",:country=>"Azerbaijan")
Country.create(:id=>17,:iso=>"BA",:country=>"Bosnia and Herzegovina")
Country.create(:id=>18,:iso=>"BB",:country=>"Barbados")
Country.create(:id=>19,:iso=>"BD",:country=>"Bangladesh")
Country.create(:id=>20,:iso=>"BE",:country=>"Belgium")
Country.create(:id=>21,:iso=>"BF",:country=>"Burkina Faso")
Country.create(:id=>22,:iso=>"BG",:country=>"Bulgaria")
Country.create(:id=>23,:iso=>"BH",:country=>"Bahrain")
Country.create(:id=>24,:iso=>"BI",:country=>"Burundi")
Country.create(:id=>25,:iso=>"BJ",:country=>"Benin")
Country.create(:id=>26,:iso=>"BL",:country=>"Saint Barthélemy")
Country.create(:id=>27,:iso=>"BM",:country=>"Bermuda")
Country.create(:id=>28,:iso=>"BN",:country=>"Brunei")
Country.create(:id=>29,:iso=>"BO",:country=>"Bolivia")
Country.create(:id=>30,:iso=>"BQ",:country=>"Bonaire, Saint Eustatius and Saba ")
Country.create(:id=>31,:iso=>"BR",:country=>"Brazil")
Country.create(:id=>32,:iso=>"BS",:country=>"Bahamas")
Country.create(:id=>33,:iso=>"BT",:country=>"Bhutan")
Country.create(:id=>34,:iso=>"BV",:country=>"Bouvet Island")
Country.create(:id=>35,:iso=>"BW",:country=>"Botswana")
Country.create(:id=>36,:iso=>"BY",:country=>"Belarus")
Country.create(:id=>37,:iso=>"BZ",:country=>"Belize")
Country.create(:id=>38,:iso=>"CA",:country=>"Canada")
Country.create(:id=>39,:iso=>"CC",:country=>"Cocos Islands")
Country.create(:id=>40,:iso=>"CD",:country=>"Democratic Republic of the Congo")
Country.create(:id=>41,:iso=>"CF",:country=>"Central African Republic")
Country.create(:id=>42,:iso=>"CG",:country=>"Republic of the Congo")
Country.create(:id=>43,:iso=>"CH",:country=>"Switzerland")
Country.create(:id=>44,:iso=>"CI",:country=>"Ivory Coast")
Country.create(:id=>45,:iso=>"CK",:country=>"Cook Islands")
Country.create(:id=>46,:iso=>"CL",:country=>"Chile")
Country.create(:id=>47,:iso=>"CM",:country=>"Cameroon")
Country.create(:id=>48,:iso=>"CN",:country=>"China")
Country.create(:id=>49,:iso=>"CO",:country=>"Colombia")
Country.create(:id=>50,:iso=>"CR",:country=>"Costa Rica")
Country.create(:id=>51,:iso=>"CU",:country=>"Cuba")
Country.create(:id=>52,:iso=>"CV",:country=>"Cape Verde")
Country.create(:id=>53,:iso=>"CW",:country=>"Curaçao")
Country.create(:id=>54,:iso=>"CX",:country=>"Christmas Island")
Country.create(:id=>55,:iso=>"CY",:country=>"Cyprus")
Country.create(:id=>56,:iso=>"CZ",:country=>"Czech Republic")
Country.create(:id=>57,:iso=>"DE",:country=>"Germany")
Country.create(:id=>58,:iso=>"DJ",:country=>"Djibouti")
Country.create(:id=>59,:iso=>"DK",:country=>"Denmark")
Country.create(:id=>60,:iso=>"DM",:country=>"Dominica")
Country.create(:id=>61,:iso=>"DO",:country=>"Dominican Republic")
Country.create(:id=>62,:iso=>"DZ",:country=>"Algeria")
Country.create(:id=>63,:iso=>"EC",:country=>"Ecuador")
Country.create(:id=>64,:iso=>"EE",:country=>"Estonia")
Country.create(:id=>65,:iso=>"EG",:country=>"Egypt")
Country.create(:id=>66,:iso=>"EH",:country=>"Western Sahara")
Country.create(:id=>67,:iso=>"ER",:country=>"Eritrea")
Country.create(:id=>68,:iso=>"ES",:country=>"Spain")
Country.create(:id=>69,:iso=>"ET",:country=>"Ethiopia")
Country.create(:id=>70,:iso=>"FI",:country=>"Finland")
Country.create(:id=>71,:iso=>"FJ",:country=>"Fiji")
Country.create(:id=>72,:iso=>"FK",:country=>"Falkland Islands")
Country.create(:id=>73,:iso=>"FM",:country=>"Micronesia")
Country.create(:id=>74,:iso=>"FO",:country=>"Faroe Islands")
Country.create(:id=>75,:iso=>"FR",:country=>"France")
Country.create(:id=>76,:iso=>"GA",:country=>"Gabon")
Country.create(:id=>77,:iso=>"GB",:country=>"United Kingdom")
Country.create(:id=>78,:iso=>"GD",:country=>"Grenada")
Country.create(:id=>79,:iso=>"GE",:country=>"Georgia")
Country.create(:id=>80,:iso=>"GF",:country=>"French Guiana")
Country.create(:id=>81,:iso=>"GG",:country=>"Guernsey")
Country.create(:id=>82,:iso=>"GH",:country=>"Ghana")
Country.create(:id=>83,:iso=>"GI",:country=>"Gibraltar")
Country.create(:id=>84,:iso=>"GL",:country=>"Greenland")
Country.create(:id=>85,:iso=>"GM",:country=>"Gambia")
Country.create(:id=>86,:iso=>"GN",:country=>"Guinea")
Country.create(:id=>87,:iso=>"GP",:country=>"Guadeloupe")
Country.create(:id=>88,:iso=>"GQ",:country=>"Equatorial Guinea")
Country.create(:id=>89,:iso=>"GR",:country=>"Greece")
Country.create(:id=>90,:iso=>"GS",:country=>"South Georgia and the South Sandwich Islands")
Country.create(:id=>91,:iso=>"GT",:country=>"Guatemala")
Country.create(:id=>92,:iso=>"GU",:country=>"Guam")
Country.create(:id=>93,:iso=>"GW",:country=>"Guinea-Bissau")
Country.create(:id=>94,:iso=>"GY",:country=>"Guyana")
Country.create(:id=>95,:iso=>"HK",:country=>"Hong Kong")
Country.create(:id=>96,:iso=>"HM",:country=>"Heard Island and McDonald Islands")
Country.create(:id=>97,:iso=>"HN",:country=>"Honduras")
Country.create(:id=>98,:iso=>"HR",:country=>"Croatia")
Country.create(:id=>99,:iso=>"HT",:country=>"Haiti")
Country.create(:id=>100,:iso=>"HU",:country=>"Hungary")
Country.create(:id=>101,:iso=>"ID",:country=>"Indonesia")
Country.create(:id=>102,:iso=>"IE",:country=>"Ireland")
Country.create(:id=>103,:iso=>"IL",:country=>"Israel")
Country.create(:id=>104,:iso=>"IM",:country=>"Isle of Man")
Country.create(:id=>105,:iso=>"IN",:country=>"India")
Country.create(:id=>106,:iso=>"IO",:country=>"British Indian Ocean Territory")
Country.create(:id=>107,:iso=>"IQ",:country=>"Iraq")
Country.create(:id=>108,:iso=>"IR",:country=>"Iran")
Country.create(:id=>109,:iso=>"IS",:country=>"Iceland")
Country.create(:id=>110,:iso=>"IT",:country=>"Italy")
Country.create(:id=>111,:iso=>"JE",:country=>"Jersey")
Country.create(:id=>112,:iso=>"JM",:country=>"Jamaica")
Country.create(:id=>113,:iso=>"JO",:country=>"Jordan")
Country.create(:id=>114,:iso=>"JP",:country=>"Japan")
Country.create(:id=>115,:iso=>"KE",:country=>"Kenya")
Country.create(:id=>116,:iso=>"KG",:country=>"Kyrgyzstan")
Country.create(:id=>117,:iso=>"KH",:country=>"Cambodia")
Country.create(:id=>118,:iso=>"KI",:country=>"Kiribati")
Country.create(:id=>119,:iso=>"KM",:country=>"Comoros")
Country.create(:id=>120,:iso=>"KN",:country=>"Saint Kitts and Nevis")
Country.create(:id=>121,:iso=>"KP",:country=>"North Korea")
Country.create(:id=>122,:iso=>"KR",:country=>"South Korea")
Country.create(:id=>123,:iso=>"XK",:country=>"Kosovo")
Country.create(:id=>124,:iso=>"KW",:country=>"Kuwait")
Country.create(:id=>125,:iso=>"KY",:country=>"Cayman Islands")
Country.create(:id=>126,:iso=>"KZ",:country=>"Kazakhstan")
Country.create(:id=>127,:iso=>"LA",:country=>"Laos")
Country.create(:id=>128,:iso=>"LB",:country=>"Lebanon")
Country.create(:id=>129,:iso=>"LC",:country=>"Saint Lucia")
Country.create(:id=>130,:iso=>"LI",:country=>"Liechtenstein")
Country.create(:id=>131,:iso=>"LK",:country=>"Sri Lanka")
Country.create(:id=>132,:iso=>"LR",:country=>"Liberia")
Country.create(:id=>133,:iso=>"LS",:country=>"Lesotho")
Country.create(:id=>134,:iso=>"LT",:country=>"Lithuania")
Country.create(:id=>135,:iso=>"LU",:country=>"Luxembourg")
Country.create(:id=>136,:iso=>"LV",:country=>"Latvia")
Country.create(:id=>137,:iso=>"LY",:country=>"Libya")
Country.create(:id=>138,:iso=>"MA",:country=>"Morocco")
Country.create(:id=>139,:iso=>"MC",:country=>"Monaco")
Country.create(:id=>140,:iso=>"MD",:country=>"Moldova")
Country.create(:id=>141,:iso=>"ME",:country=>"Montenegro")
Country.create(:id=>142,:iso=>"MF",:country=>"Saint Martin")
Country.create(:id=>143,:iso=>"MG",:country=>"Madagascar")
Country.create(:id=>144,:iso=>"MH",:country=>"Marshall Islands")
Country.create(:id=>145,:iso=>"MK",:country=>"Macedonia")
Country.create(:id=>146,:iso=>"ML",:country=>"Mali")
Country.create(:id=>147,:iso=>"MM",:country=>"Myanmar")
Country.create(:id=>148,:iso=>"MN",:country=>"Mongolia")
Country.create(:id=>149,:iso=>"MO",:country=>"Macao")
Country.create(:id=>150,:iso=>"MP",:country=>"Northern Mariana Islands")
Country.create(:id=>151,:iso=>"MQ",:country=>"Martinique")
Country.create(:id=>152,:iso=>"MR",:country=>"Mauritania")
Country.create(:id=>153,:iso=>"MS",:country=>"Montserrat")
Country.create(:id=>154,:iso=>"MT",:country=>"Malta")
Country.create(:id=>155,:iso=>"MU",:country=>"Mauritius")
Country.create(:id=>156,:iso=>"MV",:country=>"Maldives")
Country.create(:id=>157,:iso=>"MW",:country=>"Malawi")
Country.create(:id=>158,:iso=>"MX",:country=>"Mexico")
Country.create(:id=>159,:iso=>"MY",:country=>"Malaysia")
Country.create(:id=>160,:iso=>"MZ",:country=>"Mozambique")
Country.create(:id=>161,:iso=>"NA",:country=>"Namibia")
Country.create(:id=>162,:iso=>"NC",:country=>"New Caledonia")
Country.create(:id=>163,:iso=>"NE",:country=>"Niger")
Country.create(:id=>164,:iso=>"NF",:country=>"Norfolk Island")
Country.create(:id=>165,:iso=>"NG",:country=>"Nigeria")
Country.create(:id=>166,:iso=>"NI",:country=>"Nicaragua")
Country.create(:id=>167,:iso=>"NL",:country=>"Netherlands")
Country.create(:id=>168,:iso=>"NO",:country=>"Norway")
Country.create(:id=>169,:iso=>"NP",:country=>"Nepal")
Country.create(:id=>170,:iso=>"NR",:country=>"Nauru")
Country.create(:id=>171,:iso=>"NU",:country=>"Niue")
Country.create(:id=>172,:iso=>"NZ",:country=>"New Zealand")
Country.create(:id=>173,:iso=>"OM",:country=>"Oman")
Country.create(:id=>174,:iso=>"PA",:country=>"Panama")
Country.create(:id=>175,:iso=>"PE",:country=>"Peru")
Country.create(:id=>176,:iso=>"PF",:country=>"French Polynesia")
Country.create(:id=>177,:iso=>"PG",:country=>"Papua New Guinea")
Country.create(:id=>178,:iso=>"PH",:country=>"Philippines")
Country.create(:id=>179,:iso=>"PK",:country=>"Pakistan")
Country.create(:id=>180,:iso=>"PL",:country=>"Poland")
Country.create(:id=>181,:iso=>"PM",:country=>"Saint Pierre and Miquelon")
Country.create(:id=>182,:iso=>"PN",:country=>"Pitcairn")
Country.create(:id=>183,:iso=>"PR",:country=>"Puerto Rico")
Country.create(:id=>184,:iso=>"PS",:country=>"Palestinian Territory")
Country.create(:id=>185,:iso=>"PT",:country=>"Portugal")
Country.create(:id=>186,:iso=>"PW",:country=>"Palau")
Country.create(:id=>187,:iso=>"PY",:country=>"Paraguay")
Country.create(:id=>188,:iso=>"QA",:country=>"Qatar")
Country.create(:id=>189,:iso=>"RE",:country=>"Reunion")
Country.create(:id=>190,:iso=>"RO",:country=>"Romania")
Country.create(:id=>191,:iso=>"RS",:country=>"Serbia")
Country.create(:id=>192,:iso=>"RU",:country=>"Russia")
Country.create(:id=>193,:iso=>"RW",:country=>"Rwanda")
Country.create(:id=>194,:iso=>"SA",:country=>"Saudi Arabia")
Country.create(:id=>195,:iso=>"SB",:country=>"Solomon Islands")
Country.create(:id=>196,:iso=>"SC",:country=>"Seychelles")
Country.create(:id=>197,:iso=>"SD",:country=>"Sudan")
Country.create(:id=>198,:iso=>"SE",:country=>"Sweden")
Country.create(:id=>199,:iso=>"SG",:country=>"Singapore")
Country.create(:id=>200,:iso=>"SH",:country=>"Saint Helena")
Country.create(:id=>201,:iso=>"SI",:country=>"Slovenia")
Country.create(:id=>202,:iso=>"SJ",:country=>"Svalbard and Jan Mayen")
Country.create(:id=>203,:iso=>"SK",:country=>"Slovakia")
Country.create(:id=>204,:iso=>"SL",:country=>"Sierra Leone")
Country.create(:id=>205,:iso=>"SM",:country=>"San Marino")
Country.create(:id=>206,:iso=>"SN",:country=>"Senegal")
Country.create(:id=>207,:iso=>"SO",:country=>"Somalia")
Country.create(:id=>208,:iso=>"SR",:country=>"Suriname")
Country.create(:id=>209,:iso=>"ST",:country=>"Sao Tome and Principe")
Country.create(:id=>210,:iso=>"SV",:country=>"El Salvador")
Country.create(:id=>211,:iso=>"SX",:country=>"Sint Maarten")
Country.create(:id=>212,:iso=>"SY",:country=>"Syria")
Country.create(:id=>213,:iso=>"SZ",:country=>"Swaziland")
Country.create(:id=>214,:iso=>"TC",:country=>"Turks and Caicos Islands")
Country.create(:id=>215,:iso=>"TD",:country=>"Chad")
Country.create(:id=>216,:iso=>"TF",:country=>"French Southern Territories")
Country.create(:id=>217,:iso=>"TG",:country=>"Togo")
Country.create(:id=>218,:iso=>"TH",:country=>"Thailand")
Country.create(:id=>219,:iso=>"TJ",:country=>"Tajikistan")
Country.create(:id=>220,:iso=>"TK",:country=>"Tokelau")
Country.create(:id=>221,:iso=>"TL",:country=>"East Timor")
Country.create(:id=>222,:iso=>"TM",:country=>"Turkmenistan")
Country.create(:id=>223,:iso=>"TN",:country=>"Tunisia")
Country.create(:id=>224,:iso=>"TO",:country=>"Tonga")
Country.create(:id=>225,:iso=>"TR",:country=>"Turkey")
Country.create(:id=>226,:iso=>"TT",:country=>"Trinidad and Tobago")
Country.create(:id=>227,:iso=>"TV",:country=>"Tuvalu")
Country.create(:id=>228,:iso=>"TW",:country=>"Taiwan")
Country.create(:id=>229,:iso=>"TZ",:country=>"Tanzania")
Country.create(:id=>230,:iso=>"UA",:country=>"Ukraine")
Country.create(:id=>231,:iso=>"UG",:country=>"Uganda")
Country.create(:id=>232,:iso=>"UM",:country=>"United States Minor Outlying Islands")
Country.create(:id=>233,:iso=>"US",:country=>"United States")
Country.create(:id=>234,:iso=>"UY",:country=>"Uruguay")
Country.create(:id=>235,:iso=>"UZ",:country=>"Uzbekistan")
Country.create(:id=>236,:iso=>"VA",:country=>"Vatican")
Country.create(:id=>237,:iso=>"VC",:country=>"Saint Vincent and the Grenadines")
Country.create(:id=>238,:iso=>"VE",:country=>"Venezuela")
Country.create(:id=>239,:iso=>"VG",:country=>"British Virgin Islands")
Country.create(:id=>240,:iso=>"VI",:country=>"U.S. Virgin Islands")
Country.create(:id=>241,:iso=>"VN",:country=>"Vietnam")
Country.create(:id=>242,:iso=>"VU",:country=>"Vanuatu")
Country.create(:id=>243,:iso=>"WF",:country=>"Wallis and Futuna")
Country.create(:id=>244,:iso=>"WS",:country=>"Samoa")
Country.create(:id=>245,:iso=>"YE",:country=>"Yemen")
Country.create(:id=>246,:iso=>"YT",:country=>"Mayotte")
Country.create(:id=>247,:iso=>"ZA",:country=>"South Africa")
Country.create(:id=>248,:iso=>"ZM",:country=>"Zambia")
Country.create(:id=>249,:iso=>"ZW",:country=>"Zimbabwe")
Country.create(:id=>250,:iso=>"CS",:country=>"Serbia and Montenegro")
Country.create(:id=>251,:iso=>"AN",:country=>"Netherlands Antilles")

Status.create(status: "Rumour")
Status.create(status: "Storyboard")
Status.create(status: "Production")
Status.create(status: "Editing")
Status.create(status: "Released")
